### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by OmsinKrissada**
make it more precise

### CODE REVIEW

**Comment by OmsinKrissada** [comment]
Please consider these changes

**Comment by scybernaut** [comment]
please explain EXACTLY what the changes do

**Comment by OmsinKrissada** [comment]
image

**Comment by OmsinKrissada** [comment]
that's already quite precise

**Comment by OmsinKrissada** [comment]
@scybernaut i really shouldn't make joke PRs lol

**Comment by OmsinKrissada** [comment]
and now i cant delete it from my contribution list on my profile page :(

**Pull request closed without merging**
